#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Mar 10, 2020 01:46:58 PM IST  platform: Windows NT

import sys
from tkinter import messagebox
from tkinter import *
from PIL import ImageTk

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import LoginPage_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = login(root)
    LoginPage_support.init(root, top)
    root.mainloop()


w = None


def create_login(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = login(w)
    LoginPage_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_login():
    global w
    w.destroy()
    w = None


class login:

    def loginbutton(self):
        name = self.txtUser.get();
        passwd = self.txtPass.get();
        branch = self.txtBranch.get();

        if name == "Admin" and passwd == "Admin" and branch == "bank123":
            messagebox.showinfo("Login Page", "Login Successful")
        else:
            messagebox.showwarning("Login Page", "Incorrect username & password")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI Semibold} -size 9 -weight bold " \
                 "-slant roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe Print} -size 9 -weight bold -slant " \
                 "roman -underline 1 -overstrike 0"
        font9 = "-family {Segoe UI} -size 11 -weight bold -slant " \
                "italic -underline 0 -overstrike 0"

        top.geometry("725x445+450+150")
        top.title("Login Page")
        top.configure(background="#d9d9d9")

        #====== ALL Image ===========
        self.comp_logo =PhotoImage(file="image/yotta_logo.png")
        self.bg_img = PhotoImage(file="image/bg_img2.png")

        labbg=Label(top,image=self.bg_img).pack()
        #lablogo=Label(top,image=self.comp_logo).grid(row=0,column=2,pady=20)


        self.labelUser = tk.Label(top)
        self.labelUser.place(relx=0.317, rely=0.247, height=31, width=85)
        self.labelUser.configure(background="#d9d9d9")
        self.labelUser.configure(disabledforeground="#a3a3a3")
        self.labelUser.configure(font=font10)
        self.labelUser.configure(foreground="#000000")
        self.labelUser.configure(text='''User ID''')

        self.labPass = tk.Label(top)
        self.labPass.place(relx=0.317, rely=0.382, height=31, width=85)
        self.labPass.configure(background="#d9d9d9")
        self.labPass.configure(disabledforeground="#a3a3a3")
        self.labPass.configure(font=font10)
        self.labPass.configure(foreground="#000000")
        self.labPass.configure(text='''Password''')

        self.labBranch = tk.Label(top)
        self.labBranch.place(relx=0.317, rely=0.539, height=31, width=85)
        self.labBranch.configure(background="#d9d9d9")
        self.labBranch.configure(disabledforeground="#a3a3a3")
        self.labBranch.configure(font=font10)
        self.labBranch.configure(foreground="#000000")
        self.labBranch.configure(text='''Branch Code''')

        self.btnLogin = tk.Button(top)
        self.btnLogin.place(relx=0.607, rely=0.674, height=30, width=70)
        self.btnLogin.configure(activebackground="#ececec")
        self.btnLogin.configure(activeforeground="#000000")
        self.btnLogin.configure(background="#d9d9d9")
        self.btnLogin.configure(disabledforeground="#a3a3a3")
        self.btnLogin.configure(font=font9)
        self.btnLogin.configure(foreground="#000000")
        self.btnLogin.configure(highlightbackground="#d9d9d9")
        self.btnLogin.configure(highlightcolor="black")
        self.btnLogin.configure(pady="0")
        self.btnLogin.configure(text='''Login''')
        self.btnLogin.configure(command=self.loginbutton);

        self.txtUser = tk.Entry(top)
        self.txtUser.place(relx=0.579, rely=0.247, height=26, relwidth=0.200)
        self.txtUser.configure(background="white")
        self.txtUser.configure(disabledforeground="#a3a3a3")
        self.txtUser.configure(font="TkFixedFont")
        self.txtUser.configure(foreground="#000000")
        self.txtUser.configure(insertbackground="black")

        self.txtPass = tk.Entry(top)
        self.txtPass.place(relx=0.579, rely=0.404, height=26, relwidth=0.200)
        self.txtPass.configure(background="white")
        self.txtPass.configure(disabledforeground="#a3a3a3")
        self.txtPass.configure(font="TkFixedFont")
        self.txtPass.configure(foreground="#000000")
        self.txtPass.configure(insertbackground="black")

        self.txtBranch = tk.Entry(top)
        self.txtBranch.place(relx=0.579, rely=0.539, height=26, relwidth=0.200)
        self.txtBranch.configure(background="white")
        self.txtBranch.configure(disabledforeground="#a3a3a3")
        self.txtBranch.configure(font="TkFixedFont")
        self.txtBranch.configure(foreground="#000000")
        self.txtBranch.configure(insertbackground="black")

        self.Labcomp = tk.Label(top)
        self.Labcomp.place(relx=0.65, rely=0.921, height=31, width=240)
        self.Labcomp.configure(background="#d9d9d9")
        self.Labcomp.configure(disabledforeground="#a3a3a3")
        self.Labcomp.configure(font=font12)
        self.Labcomp.configure(foreground="#000000")
        self.Labcomp.configure(text='''powered by : Yotta softech solution''')

        #self.LabLogo = tk.Label(top)
        #self.LabLogo.place(height=120, width=120)
        #root = Tk()
        #photo = PhotoImage(file = r"E:\Bank_project\yotta_logo.gif")
        #self.LabLogo = photo.pack(side = LEFT)
        #LabLogo = grid()
        #LabLogo = tk.Label(top, image = photo).pack(side = LEFT)







if __name__ == '__main__':
    vp_start_gui()
