#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Mar 21, 2020 03:36:53 PM IST  platform: Windows NT
set vTcl(timestamp) ""


set image_list { \
    start_botton_new_png ./image/start-botton_new.png \
}
   vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background $vTcl(actual_gui_bg) \
        -highlightbackground #6ed8d8 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1038x773+315+133
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1020
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Main Page"
    vTcl:DefineAlias "$top" "main_page" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men49" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label Report 
    menu $site_3_0.men49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label GL 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label eJ 
    $site_3_0.men49 add separator \
        -background $vTcl(pr,menubgcolor) 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label eJFinTxn 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label eJNotInGL 
    $site_3_0.men49 add separator \
        -background $vTcl(pr,menubgcolor) 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label NotInHost 
    $site_3_0.men49 add separator \
        -background $vTcl(pr,menubgcolor) 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label OTHonUSGLTxn 
    $site_3_0.men49 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label USonUSGLTxn 
    $site_3_0 add cascade \
        -menu "$site_3_0.men49" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label Report -menu "$site_3_0.men51" \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Help 
    menu $site_3_0.men51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font {-family {Segoe UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men51 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label Guide 
    $site_3_0.men51 add separator \
        -background $vTcl(pr,menubgcolor) 
    $site_3_0.men51 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -label {About us} 
    frame $top.fra52 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 345 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1005 
    vTcl:DefineAlias "$top.fra52" "Frame1" vTcl:WidgetProc "main_page" 1
    set site_3_0 $top.fra52
    button $site_3_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Clear Data} 
    vTcl:DefineAlias "$site_3_0.but57" "btn_clear" vTcl:WidgetProc "main_page" 1
    button $site_3_0.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Import eJ} 
    vTcl:DefineAlias "$site_3_0.but43" "btn_imp_ej" vTcl:WidgetProc "main_page" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Import GL} 
    vTcl:DefineAlias "$site_3_0.but48" "btn_imp_gl" vTcl:WidgetProc "main_page" 1
    place $site_3_0.but57 \
        -in $site_3_0 -x 600 -y 200 -width 118 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 410 -y 200 -width 118 -height 42 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 230 -y 200 -width 118 -height 42 -anchor nw \
        -bordermode ignore 
    frame $top.fra53 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 265 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 715 
    vTcl:DefineAlias "$top.fra53" "Frame2" vTcl:WidgetProc "main_page" 1
    set site_3_0 $top.fra53
    button $site_3_0.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image start_botton_new_png -pady 0 
    vTcl:DefineAlias "$site_3_0.but58" "btn_recon" vTcl:WidgetProc "main_page" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -underline 1} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Data Processing} 
    vTcl:DefineAlias "$site_3_0.lab60" "lab_process" vTcl:WidgetProc "main_page" 1
    place $site_3_0.but58 \
        -in $site_3_0 -x 250 -y 110 -width 198 -relwidth 0 -height 52 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 240 -y 10 -width 187 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 17 -weight bold -underline 1} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ATM RECONCILIATION} 
    vTcl:DefineAlias "$top.lab54" "Lab_atm" vTcl:WidgetProc "main_page" 1
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant italic -underline 1} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {powered by: Yotta softech solution} 
    vTcl:DefineAlias "$top.lab61" "lab_comp1" vTcl:WidgetProc "main_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra52 \
        -in $top -x 20 -y 50 -width 1005 -relwidth 0 -height 345 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 160 -y 410 -width 715 -relwidth 0 -height 265 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 200 -y 60 -width 667 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 710 -y 740 -width 307 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

